### ISSUE TITLE
 "every 16ms or more" should be "every 16ms or less"

### ISSUE THREAD

**Issue by Raptorel** [googlecodelabs/kotlin-coroutines#109]
The typo is in Chapter 4, "Coroutines in Kotlin", where there is a hyperlink to the medium article.

**Comment by wojtek-kalicinski** [comment]
Thank you, I've corrected the text in the internal codelab source document and it will be visible soon, once we publish a new version on the website.

**Comment by B-Lidberg** [comment]
It's still visible on the Codelab and was updated in February? Still not resolved
